Datos/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Route::get('/datos', 'DatosController@index')->name('datos');
Route::resource('datos','DatosController');

Datos/app/Dato.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dato extends Model
{
    //
}

Datos/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

Datos/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

Datos/app/Http/Controllers/DatosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Dato;

class DatosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $datos = Dato::all();
        return view('datos.index',['dato'=>$datos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('datos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $dato = new Dato();
        $dato->nombre = $request->nombre;
        $dato->apellidop = $request->apellidop;
        $dato->apellidom = $request->apellidom;
        $dato->fecha = $request->fecha;

        if ($dato->save()){
            return redirect('/datos');
        }else{
            return view('datos.create');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $dato = Dato::find($id);
        return view('datos.edit',['dato'=>$dato]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $dato = Dato::find($id);
        $dato->nombre = $request->nombre;
        $dato->apellidop = $request->apellidop;
        $dato->apellidom = $request->apellidom;
        $dato->fecha = $request->fecha;

        if ($dato->save()){
            return redirect('datos');
        }else{
            return view('datos.edit',['dato'=>$dato]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Dato::destroy($id);
        return redirect('/datos');
    }
}

Datos/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

Datos/resources/views/datos/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 style="text-align: center">Datos Personales</h1>
                <form action="{{route('datos.store')}}" method="post">
                @csrf
                    <div class="form-group">
                        <label for="exampleInputEmail1">Nombre</label>
                        <input name="nombre" type="text" class="form-control" id="nombre">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Apellido Paterno</label>
                        <input name="apellidop" type="text" class="form-control" id="apellidop">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Apellido Materno</label>
                        <input name="apellidom" type="text" class="form-control" id="apellidom">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Fecha de Nacimiento</label>
                        <input name="fecha" type="date" class="form-control" id="fecha">
                    </div>
                    <input type="submit" class="btn btn-primary" value="Guardar">
                </form>
            </div>
        </div>
    </div>
@endsection

Datos/resources/views/datos/delete.blade.php
<form action="{{url('/datos/'.$d->id)}}" method="post" class="d-inline-block">
    {{method_field('DELETE')}}
    @csrf
    <input type="submit" class="btn btn-link" style="color: red" value="Eliminar">
</form>

Datos/resources/views/datos/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 style="text-align: center">Datos Personales</h1>
                <form action="{{url(route('datos.update',$dato->id))}}" method="post">
                    {{method_field('PATCH')}}
                    @csrf
                    <div class="form-group">
                        <label for="">Nombre</label>
                        <input value="{{$dato->nombre}}" name="nombre" type="text" class="form-control" id="nombre">
                    </div>
                    <div class="form-group">
                        <label for="">Apellido Paterno</label>
                        <input value="{{$dato->apellidop}}" name="apellidop" type="text" class="form-control" id="apellidop">
                    </div>
                    <div class="form-group">
                        <label for="">Apellido Materno</label>
                        <input value="{{$dato->apellidom}}" name="apellidom" type="text" class="form-control" id="apellidom">
                    </div>
                    <div class="form-group">
                        <label for="">Fecha de Nacimiento</label>
                        <input value="{{$dato->fecha}}" name="fecha" type="date" class="form-control" id="fecha">
                    </div>
                    <input type="submit" class="btn btn-primary" value="Guardar">
                </form>
            </div>
        </div>
    </div>
@endsection

Datos/resources/views/datos/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1>Registros</h1>
                <table class="table">
                    <thead class="thead-dark">
                    <tr>
                        <th>ID</th>
                        <th>NOMBRE</th>
                        <th>APELLIDO PATERNO</th>
                        <th>APELLIDO MATERNO</th>
                        <th>FECHA NACIMIENTO</th>
                        <th style="text-align: center">ACCION</th>
                    </tr>
                    </thead>
                    @foreach($dato as $d)
                        <tr>
                            <td align="center">{{$d->id}}</td>
                            <td align="center">{{$d->nombre}}</td>
                            <td align="center">{{$d->apellidop}}</td>
                            <td align="center">{{$d->apellidom}}</td>
                            <td align="center">{{$d->fecha}}</td>
                            <td style="background-color: lightblue">
                                <a href="{{url('/datos/'.$d->id.'/edit')}}" class="btn btn-link">Editar</a>
                                @include('datos.delete',['$dato' => $d])
                            </td>
                        </tr>
                    @endforeach
                </table>
                <form action="{{route('datos.create')}}" method="get">
                    <input class="btn btn-success" type="submit" value="Nuevo">
                </form>
            </div>
        </div>
    </div>
@endsection

Datos/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

Datos/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>